parsed_test_dir: "/data/output/parsed_tests"
results_dir: "data/output/evaluation/craftdroid"
logs_dir: "/data/output/logs"
analyse_dir: "data/output/analyse"
tests:
  atm:
    dir: "./data/atm_tests"
    file_globs: 
      - "*/*/*.java"
      - "ground_truth/*/*.json"
  craftdroid:
    dir: "./data/craftdroid_tests"
    file_globs: 
      - "*/b*2/base/*.json"
      - "a3/b31/base/*.json"
      - "a4/b41/base/*.json"

