migration_plan_path: "migrations.csv"
results: "results.csv"
clean_file: "clean.sh"
atm_root: "/root/test-reuse/atm/ATM-Modified"
migration_log_dir: "log"
generated_dir: "generated"
config_samples: 'config_sample.csv'
emulator: "emulator1"
migration_timeout: 3600
install_timeout: 240
embedding:
  - wm
  - w2v
  - nnlm
  - use
  - bert
  - glove
  - fast
  - jaccard
  - edit_distance
  - random
train_set:
  - android
  - blogs
  - standard
  - empty
  - googleplay
algorithm:
  - craftdroid
  - custom
  - atm
  - perfect
  - adaptdroid
  - random
descriptors:
  - union
  - intersection
  - craftdroid
  - atm
