#parsed_test_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/data/parsed_test"
parsed_test_dir: "/data/output/parsed_tests"
results_dir: "data/json_tests"
# logs_dir: "/root/test-reuse/Craftdroid-Modified/test_attribute_extractor/data/output/logs"
#logs_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/test_attribute_extractor/data/output/logs"
logs_dir: "data/output/logs"
analyse_dir: "data/output/analyse/"
tests:
  atm:
    dir: "./data/original_tests/atm"
    file_globs: 
  #     # - "*/*/*.java"
      - "ground_truth/*/*.json"
  #     # - "donor/*/*.java"
  craftdroid:
    dir: "./data/original_tests/craftdroid"
    file_globs: 
      # - "*/b*2/base/*.json"
      # - "a3/b31/base/*.json"
      # - "a4/b41/base/*.json"
      - "donor/a5*.json"

