
algorithm = 'atm'

[atm]
[atm.MIGRATION_CONFIGS]
address = '../data/original_tests/atm/generated/*'
erroneous_address = '../data/broken_tests/atm/'

[atm.src_gt]
oracles_excluded = "../data/mappings/atm/src_ground_truth/oracles_excluded/src_ground_truth.csv"
oracles_included = "../data/mappings/atm/src_ground_truth/oracles_included/src_ground_truth.csv"
oracles_only = "../data/mappings/atm/src_ground_truth/oracles_only/src_ground_truth.csv"

[atm.gt_gen]
address = "../data/mappings/atm/ground_truth_generated/"

[atm.result]
oracles_excluded = "../data/output/evaluation/atm/oracles_excluded/"
oracles_included = "../data/output/evaluation/atm/oracles_included/"
oracles_only = "../data/output/evaluation/atm/oracles_only/"
aggregated_result_address = "../data/output/analyse/atm/atm_aggregated_result.csv"

[atm.BASE_JSON_ADDRESS]
address = '../data/json_tests/atm/'
generated = '../data/json_tests/atm/generated/'

[atm.BASE_LOG_ADDRESS]
address = '../data/output/logs/atm/'
generated = '../data/output/logs/atm/generated/'

[atm.GROUND_TRUTH_GLOBE]
address = '../data/json_tests/atm/ground_truth/*/*.json'




[craftdroid]
[craftdroid.MIGRATION_CONFIGS]
address = '../data/original_tests/craftdroid/generated/*'
erroneous_address = '../data/broken_tests/craftdoid/'

[craftdroid.src_gt]
oracles_excluded = "../data/mappings/craftdroid/src_ground_truth/oracles_excluded/src_ground_truth.csv"
oracles_included = "../data/mappings/craftdroid/src_ground_truth/oracles_included/src_ground_truth.csv"
oracles_only = "../data/mappings/craftdroid/src_ground_truth/oracles_only/src_ground_truth.csv"

[craftdroid.gt_gen]
address = "../data/mappings/craftdroid/ground_truth_generated/"

[craftdroid.result]
oracles_excluded = "../data/output/evaluation/craftdroid/oracles_excluded/"
oracles_included = "../data/output/evaluation/craftdroid/oracles_included/"
oracles_only = "../data/output/evaluation/craftdroid/oracles_only/"
aggregated_result_address = "../data/output/analyse/craftdroid/craftdroid_aggregated_result.csv"

[craftdroid.BASE_JSON_ADDRESS]
address = '../data/original_tests/craftdroid/'
generated = '../data/original_tests/craftdroid/generated/'

[craftdroid.BASE_LOG_ADDRESS]
address = '../data/output/logs/craftdroid/'
generated = '../data/output/logs/craftdroid/generated/'

[craftdroid.GROUND_TRUTH_GLOBE]
address = '../data/original_tests/craftdroid/ground_truth/*.json'

    
