parsed_test_dir: "/data/output/parsed_tests"
results_dir: "data/output/evaluation/craftdroid/oracles_included/"
logs_dir: "data/output/logs"
analyse_dir: "data/output/analyse/"
tests:
  atm:
    dir: "./data/original_tests/atm"
    file_globs:
      #     # - "*/*/*.java"
      - "ground_truth/*/*.json"
  #     # - "donor/*/*.java"
  craftdroid:
    dir: "./data/original_tests/craftdroid"
    file_globs:
      # - "*/b*2/base/*.json"
      # - "a3/b31/base/*.json"
      # - "a4/b41/base/*.json"
      - "donor/a5*.json"
