root: "/root/test-reuse/Craftdroid-Modified/"
#root: "/Users/usiusi/Documents/Repositories/Craftdroid/craft_custom/"
apks_dir: "/Users/usiusi/Documents/Repositories/Craftdroid/subject_apps"
decompile_temp: 'apk_decompiled_temp'
image_repo: 'image_file_name_repo'
sm_conf_path: 'matching_client/sm_config'
config_samples: 'manager/config_sample.csv'
emulator: "emulator1"
appium_port: '4723'
migration_plan_path: "manager/migrations.csv"
results: "manager/results.csv"
migration_log_dir: "log"
generated_dir: "manager/generated"
migration_timeout: 9000
embedding:
  - wm
  - w2v
  - nnlm
  - use
  - bert
  - glove
  - fast
  - jaccard
  - edit_distance
  - random
train_set:
  - android
  - blogs
  - standard
  - empty
  - googleplay
algorithm:
  - craftdroid
  - custom
  - atm
  - perfect
  - adaptdroid
  - random
descriptors:
  - union
  - intersection
  - craftdroid
  - atm
